# Generated by Django 3.0.2 on 2020-01-28 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('national_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='CourierLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_FactorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factor_IngredientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factor_MenuLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerCommentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('food_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='MenuLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Account',
            fields=[
                ('shop_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_AccountLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop_FactorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('national_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCommentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('key', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_action', models.CharField(blank=True, max_length=300, null=True)),
                ('after_action', models.CharField(blank=True, max_length=300, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.User')),
            ],
        ),
        migrations.CreateModel(
            name='Shop_Factor',
            fields=[
                ('factor_number', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.Shop_Account')),
            ],
            options={
                'unique_together': {('shop_name', 'order_time')},
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('shop_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.Shop_Account')),
            ],
            options={
                'unique_together': {('shop_name', 'item_name')},
            },
        ),
        migrations.CreateModel(
            name='Customer_Factor',
            fields=[
                ('factor_number', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.Courier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.User')),
            ],
        ),
        migrations.CreateModel(
            name='Factor_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.Customer_Factor')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.Menu')),
            ],
            options={
                'unique_together': {('factor', 'food_name')},
            },
        ),
        migrations.CreateModel(
            name='Factor_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.Shop_Factor')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB_app_label.Ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'factor')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=20)),
                ('address_path', models.CharField(max_length=200)),
                ('fixed_phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='DB_app_label.User')),
            ],
            options={
                'unique_together': {('address_name', 'user')},
            },
        ),
    ]
