from django.conf.urls import url
from DB_app import views

urlpatterns = [
    url(r'^inserts_list$', views.inserts_list, name="inserts_list"),
    url(r'^updates_list$', views.updates_list, name="updates_list"),
    url(r'^insert_into_user$', views.insert_into_user, name="insert_into_user"),
    url(r'^insert_into_Courier$', views.insert_into_Courier, name="insert_into_Courier"),
    url(r'^insert_into_address$', views.insert_into_address, name="insert_into_address"),
    url(r'^insert_into_menu$', views.insert_into_menu, name="insert_into_menu"),
    url(r'^insert_into_customer_factor$', views.insert_into_customer_factor, name="insert_into_customer_factor"),
    url(r'^insert_into_ingredient$', views.insert_into_ingredient, name="insert_into_ingredient"),
    url(r'^insert_into_shop_factor$', views.insert_into_shop_factor, name="insert_into_shop_factor"),
    url(r'^insert_into_shop_account$', views.insert_into_shop_account, name="insert_into_shop_account"),
    url(r'^insert_into_factor_menu$', views.insert_into_factor_menu, name="insert_into_factor_menu"),
    url(r'^insert_into_factor_ingredient$', views.insert_into_factor_ingredient, name="insert_into_factor_ingredient"),
    url(r'^insert_into_user_comment$', views.insert_into_user_comment, name="insert_into_user_comment"),
    url(r'^insert_into_manager_comment$', views.insert_into_manager_comment, name="insert_into_manager_comment"),

    url(r'^deletes_list$', views.deletes_list, name="deletes_list"),
    url(r'^delete_user_list$', views.delete_user_list, name="delete_user_list"),
    url(r'^delete_Courier_list$', views.delete_Courier_list, name="delete_Courier_list"),
    url(r'^delete_address_list$', views.delete_address_list, name="delete_address_list"),
    url(r'^delete_menu_list$', views.delete_menu_list, name="delete_menu_list"),
    url(r'^delete_customer_factor_list$', views.delete_customer_factor_list, name="delete_customer_factor_list"),
    url(r'^delete_ingredient_list$', views.delete_ingredient_list, name="delete_ingredient_list"),
    url(r'^delete_shop_factor_list$', views.delete_shop_factor_list, name="delete_shop_factor_list"),
    url(r'^delete_shop_account__list$', views.delete_shop_account_list, name="delete_shop_account__list"),
    url(r'^delete_factor_menu_list$', views.delete_factor_menu_list, name="delete_factor_menu_list"),
    url(r'^delete_factor_ingredient_list$', views.delete_factor_ingredient_list, name="delete_factor_ingredient_list"),

    url(r'^delete_user/(?P<pk>\d+)$', views.delete_user, name="delete_user"),
    url(r'^delete_Courier/(?P<pk>\d+)$', views.delete_Courier, name="delete_Courier"),
    url(r'^delete_address/(?P<pk>\d+)$', views.delete_address, name="delete_address"),
    url(r'^delete_menu/(?P<pk>\d+)$', views.delete_menu, name="delete_menu"),
    url(r'^delete_customer_factor/(?P<pk>\d+)$', views.delete_customer_factor, name="delete_customer_factor"),
    url(r'^delete_ingredient/(?P<pk>\w+)$', views.delete_ingredient, name="delete_ingredient"),
    url(r'^delete_shop_factor/(?P<pk>\d+)$', views.delete_shop_factor, name="delete_shop_factor"),
    url(r'^delete_shop_account/(?P<pk>\w+)$', views.delete_shop_account, name="delete_shop_account"),
    url(r'^delete_factor_menu/(?P<pk>\w+)$', views.delete_factor_menu, name="delete_factor_menu"),
    url(r'^delete_factor_ingredient/(?P<pk>\w+)$', views.delete_factor_ingredient, name="delete_factor_ingredient"),

    url(r'^updates_list$', views.updates_list, name="updates_list"),
    url(r'^update_user$', views.update_user, name="update_user"),
    url(r'^update_Courier$', views.update_Courier, name="update_Courier"),
    url(r'^update_address$', views.update_address, name="update_address"),
    url(r'^update_menu$', views.update_menu, name="update_menu"),
    url(r'^update_customer_factor$', views.update_customer_factor, name="update_customer_factor"),
    url(r'^update_ingredient$', views.update_ingredient, name="update_ingredient"),
    url(r'^update_shop_factor$', views.update_shop_factor, name="update_shop_factor"),
    url(r'^update_shop_account$', views.update_shop_account, name="update_shop_account"),
    url(r'^update_factor_ingredient$', views.update_factor_ingredient, name="update_factor_ingredient"),
    url(r'^update_factor_menu$', views.update_factor_menu, name="update_factor_menu"),


    url(r'^requirements_list$', views.requirements_list, name="requirements_list"),
    url(r'^order_food$', views.order_food, name="order_food"),
    url(r'^order_ingredient$', views.order_ingredient, name="order_ingredient"),
    url(r'^show_user_list$', views.show_user_list, name="show_user_list"),
    url(r'^show_user_orders/(?P<pk>\d+)$', views.show_user_orders, name="show_user_orders"),
    url(r'^show_restaurant_orders$', views.show_restaurant_orders, name="show_restaurant_orders"),
    url(r'^show_cost_benefit$', views.show_cost_benefit, name="show_cost_benefit"),
    url(r'^show_user_comments$', views.show_user_comments, name="show_user_comments"),
    url(r'^show_manager_comments$', views.show_manager_comments, name="show_manager_comments"),
    url(r'^show_user_comments$', views.show_user_comments, name="show_user_comments"),
]